name: Build Container and Push to Contensis

on:
  pull_request:
    branches: [ "publish" ]
  push:
    branches: [ "publish" ]
  workflow_dispatch:
  
env:
    IMAGE_NAME: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app
    IMAGE_TAGS: build-${{ github.run_number }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      # login to registry
      - name: Log into container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }}

  push_to_contensis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Contensis block push action
        uses: contensis/block-push@v1
        with:
          alias: staffscc
          block-id: master-has-given-dobby-a-block
          client-id: ${{ secrets.Z_CLIENT_ID }}
          git-token: ${{ github.token }}
          image-uri: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }}
          project-id: sodorparishcouncil
          shared-secret: ${{ secrets.Z_SHARED_SECRET }}
